### ISSUE TITLE
Project status/passing action to notify callback

### ISSUE THREAD

**Issue by MattKunze** [tappleby/redux-batched-subscribe#20]
I see there are three open PRs for passing the action being dispatched to the notify callback (#6, #13, #17) - any updates about your thoughts regarding a change like that?

This enhancer gives us great perf wins for our application, but there are a handful of actions dispatched by keyboard input that we need to notify subscribers immediately or things get laggy and cause other input issues.

Please don't take this as being critical or nagging, I know everyone is busy and OSS projects can easily become time sinks, I'm just looking to see whether I should maintain a separate fork or your goals are to continue maintaining this project.

**Comment by tappleby** [comment]
I havent had time recently to focus on this project but I plan on getting back to it soon. 

I had originally not wanted to add support for passing the action to the notify callback because it deviated from how subscribe handlers currently work. 

After thinking about it some more and looking at the number of requests + forks, I think its a good thing to have.

**Comment by MattKunze** [comment]
Thanks for the reply. I'll watch for updates and switch back to main version once something like that lands
