### ISSUE TITLE
A couple of questions

### ISSUE THREAD

**Issue by janusch** [tappleby/redux-batched-subscribe#3]
Hey,
first of all, thank you very much for creating this library!
It addresses exactly a problem that I am facing in my app.

As I understood from this PR, https://github.com/acdlite/redux-batched-updates/pull/3 ,  this library is the successor of `redux-batched-updates` , right?

I first could not get your library to work following the example of the readme. Now it works using the debounce method and removing the logger middleware `redux-logger` , since the logger is turned off in production and that is where batched updates matter the most it is not a big deal though. Is there a workaround for this issue though?

Now my issue is, which i believe is still a quite common use case, I am fetching data from 100 different endpoints and would like to render the data above the fold when it arrives, and batch update the rest in chunks.
The way it works with your fantastic library is that when using batched updates it waits until all 100 requests have completed. How can I make the first render after, say the first 4-5 requests have completed?
Is there a way to get a bit more fine grained control about the updates I would like to have batched, e.g. batch excessive data fetching, but not ordinary user interaction, etc.

Would love to hear your point of view and if you see a way to solve these issues!

Keep up the great work,
Cheers!

**Comment by tappleby** [comment]
This library isnt necessarily a successor of `redux-batched-updates`, just a more generic version. It gives control of when subscription handlers get notified. Its main focus is for preventing unnecessary renders in React.

Your issue with the middleware might be related to #2, Ive been meaning to merge this.

Instead of lower level render batching I think your looking for a way to group/batch actions. Im not sure if an exact solution exists for what you want yet, but [redux-combine-actions](https://github.com/itsmepetrov/redux-combine-actions) or [redux-batched-actions](https://github.com/tshelburne/redux-batched-actions) might get you in the right direction. 

If I was looking at implementing this, I would setup the UI to render whatever data is currently stored in state; then on startup or in `componentDidMount` on a container component, dispatch actions for loading data (in batches of X requests).

The logic for "first render after, say the first 4-5 requests have completed?" becomes just checking the state to see if enough data has been loaded yet.

Things do get a bit more complicated since requests can complete out of order, or just fail.

If you control the endpoints it can be also worth looking into ways to reduce the number of requests you need to make.

**Comment by janusch** [comment]
Thank you very much for the in depth reply @tappleby !

I am going to have a look at the batched actions.

Is it possible to use redux-batched-subscribe for just a state slice, or in which cases is it convenient to to batch all subscribes?
Is there an example project where I could see the full benefit of using redux-batched-subscribe?

Thanks again for your reply!

**Comment by jugimaster** [comment]
Does anyone else think it's weird that there are _eight_ different configuration files for various tools, all for one file of source code that implements the actual library?

I don't understand how people just calmly accept this proliferation of "unnecessary" files.

**Comment by janusch** [comment]
@jugimaster now you have taken this off topic with your .dotfiles issue that it needs to get closed :(

**Comment by jugimaster** [comment]
That makes no sense, and the topic was actually: "A couple of questions" .. I asked a question.

**Comment by janusch** [comment]
@jugimaster haha, good one! You are completely right the topic was stated too broad.
I agree with you on the config issue.

Merry, merry

**Comment by tappleby** [comment]
@janusch I had a response prepared which I forgot to send!

Its not possible to batch only for a single state slice, redux-batch-subscribe isnt really aware of state or what has changed. [redux-skip-by-action](https://github.com/tshelburne/redux-skip-by-action) is built using this lib, it allows you to skip subscribe notification for some actions (though I'm not sure there are many use cases you would want to do this.)

There is no official example project but a github search does [show some projects using it](https://github.com/search?utf8=%E2%9C%93&q=from+redux-batched-subscribe&type=Code&ref=searchresults).

**Comment by tappleby** [comment]
@jugimaster @janusch I do agree about the dotfile issue as well, reminds me of this tweet: https://twitter.com/iamdevloper/status/619459107519614976

> You know you’re looking at a JavaScript project in 2015 when there’s more dotfiles than source files.
> — @iamdevloper

With the project in its current form each one does serve a purpose except for maybe `.editorconfig`, at least the number of files stays pretty much consistent no matter the size of the project. 

For a library of this size, the only solution I see is to just use ES5.
