### ISSUE TITLE
Delay slice()ing the listeneres

### ISSUE THREAD

**Issue by gaearon** [tappleby/redux-batched-subscribe#8]
Redux introduced a few optimizations in 3.x, and we now delay `slice()`ing listeners unless absolutely necessary, and don’t `slice()` them more than once per `dispatch()`. This project should probably adopt similar optimizations.

**Comment by tappleby** [comment]
Thanks for the heads up.

Was just looking over the redux release log an these look like the major changes:

reactjs/redux@b7031ce3acb23b6ecadbd977b1cfa32486447904
reactjs/redux#1325
reactjs/redux@c031c0a8d900e0e95a4915ecc0f96c6fe2d6e92b
reactjs/redux@5b586080b43ca233f78d56cbadf706c933fefd19

I wonder if I can avoid duplicating this logic by wrapping the listener callback instead of reimplementing the subscribe logic.

**Comment by gaearon** [comment]
Give it a try, let me know if there’s something I can do on our side

**Comment by tappleby** [comment]
So I ended up implementing both. Not sure if wrapping the listener ends up simplifying things, still end up needing all the tests as a regression.

Direct port of redux core: 4093d5c783f04192f9337e15ad1b8eba487d7308
Experimental version: ad8935d72d180e1e867091fc2e1afff9f3dea898

One idea on the redux side that could help is moving the subscription logic into a util function this library could consume: tappleby/redux@6ca7c8d265afa2d8521fcf6f4a62d8086f4a9aff

**Comment by gaearon** [comment]
Mind publishing this emitter on npm?

**Comment by tappleby** [comment]
I can, though does it make sense as a standalone package? 

Also there's a bunch of emitters already on npm, wonder if it should be scoped to redux. eg redux-emitter or redux-core-emitter.

**Comment by tappleby** [comment]
So I merged the direct port (4093d5c) and released with v0.1.5. Wasnt sure the timeline for reactjs/redux#1702, plus these optimizations will still be useful for non redux v4 users.

**Comment by gaearon** [comment]
:+1:
