### ISSUE TITLE
Explain the purpose of using unstable_batchedUpdates when already using redux-batched-subscribe

### ISSUE THREAD

**Issue by gajus** [tappleby/redux-batched-subscribe#9]
@tappleby What is the difference between a generic handler such as `debounce`/ `throttle` and use of `batchedUpdates` to control dispatching of events?

**Comment by tappleby** [comment]
Using reacts `batchedUpdates` will prevent cascading renders in react components if dispatching in componentWillMount or componentDidMount see these for more details:
- http://fluxxor.com/guides/react.html
- https://github.com/reactjs/redux/issues/125#issuecomment-112779483

I haven't confirmed this recently but I remember when first working on this package, batchedUpdates would trigger the callback right away when outside the render cycle, which meant dispatching consecutive actions right after each other would still trigger multiple subscription notifications; This is where `debounce` is useful since it will ensure only 1 subscription notification happens per tick.

**Comment by gajus** [comment]
> Using reacts batchedUpdates will prevent cascading renders in react components if dispatching in componentWillMount or componentDidMount see these for more details:

Ok. This is the key information. Please add it to the documentation.

Thank you for explaining.
